ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP WITH TIME ZONE NULL; -- Can switch to NOT NULL in future migration if needed
