// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Restaurant struct {
	ID        string
	Name      string
	Address   string
	Phone     string
	Email     string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}
