// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package sqlc

import (
	"context"
	"time"
)

const createRestaurant = `-- name: CreateRestaurant :exec
INSERT INTO restaurants (id, name, address, phone, email, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateRestaurantParams struct {
	ID        string
	Name      string
	Address   string
	Phone     string
	Email     string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) error {
	_, err := q.db.Exec(ctx, createRestaurant,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
